import { z } from 'zod'
import { COMPANY_STATUSES, FOLLOW_UP_STATUSES, INTERACTION_TYPES, OPPORTUNITY_STAGES, OPPORTUNITY_TYPES, PRIORITIES, ROLES } from './domain'

const optionalUrl = z.union([z.string().url(), z.literal('')]).optional().nullable()
export const companySchema = z.object({ name: z.string().trim().min(1).max(200), industry: z.string().trim().max(120).optional().nullable(), size: z.string().trim().max(80).optional().nullable(), headquarters: z.string().trim().max(160).optional().nullable(), website: optionalUrl, description: z.string().max(4000).optional().nullable(), status: z.enum(COMPANY_STATUSES).default('Prospect'), notes: z.string().max(10000).optional().nullable(), tags: z.array(z.string().trim().min(1).max(40)).max(30).default([]) })
export const contactSchema = z.object({ companyId: z.string().uuid(), firstName: z.string().trim().min(1).max(100), lastName: z.string().trim().max(100).default(''), title: z.string().trim().max(120).optional().nullable(), department: z.string().trim().max(120).optional().nullable(), email: z.union([z.string().email(), z.literal('')]).optional().nullable(), phone: z.string().trim().max(40).optional().nullable(), linkedin: optionalUrl, preferredCommunication: z.string().trim().max(40).optional().nullable(), isPrimary: z.boolean().default(false) })
export const interactionSchema = z.object({ companyId: z.string().uuid(), contactId: z.string().uuid().optional().nullable(), initiativeId: z.string().uuid().optional().nullable(), opportunityId: z.string().uuid().optional().nullable(), type: z.enum(INTERACTION_TYPES), date: z.coerce.date(), participants: z.array(z.string().trim().max(160)).max(100).default([]), notes: z.string().trim().min(1).max(20000), outcome: z.string().max(10000).optional().nullable(), nextAction: z.string().max(2000).optional().nullable(), followUpDate: z.coerce.date().optional().nullable() })
export const followUpSchema = z.object({ companyId: z.string().uuid(), interactionId: z.string().uuid().optional().nullable(), initiativeId: z.string().uuid().optional().nullable(), officerId: z.string().uuid().optional().nullable(), title: z.string().trim().min(1).max(240), description: z.string().max(10000).optional().nullable(), dueDate: z.coerce.date().optional().nullable(), priority: z.enum(PRIORITIES).default('Medium'), status: z.enum(FOLLOW_UP_STATUSES).default('Pending'), reminderSchedule: z.string().max(80).optional().nullable() })
export const opportunitySchema = z.object({ companyId: z.string().uuid(), initiativeId: z.string().uuid().optional().nullable(), initiativeOwnerId: z.string().uuid().optional().nullable(), title: z.string().trim().min(1).max(240), type: z.enum(OPPORTUNITY_TYPES).default('Other'), stage: z.enum(OPPORTUNITY_STAGES).default('Prospect'), probability: z.coerce.number().int().min(0).max(100).nullable().optional(), expectedClose: z.coerce.date().optional().nullable(), notes: z.string().max(10000).optional().nullable() })
export const userRoleSchema = z.object({ userId: z.string().uuid(), role: z.enum(ROLES) })

export function formString(formData: FormData, key: string): string | null { const value = formData.get(key); return typeof value === 'string' && value.trim() ? value.trim() : null }
export function formBoolean(formData: FormData, key: string): boolean { return formData.get(key) === 'true' || formData.get(key) === 'on' }
export function formArray(formData: FormData, key: string): string[] { return formData.getAll(key).filter((value): value is string => typeof value === 'string').flatMap(value => value.split(',')).map(value => value.trim()).filter(Boolean) }
