'use client'

import { useState } from 'react'
import { CheckCircle2, ExternalLink, Loader2, Search } from 'lucide-react'
import { researchCompanyWebsite, saveCompanyEnrichment } from '@/app/actions/company-data'

type Enrichment = { ceo?: string | null; founders?: string[]; foundingYear?: number | null; sources?: { label: string; url: string }[] }
export function CompanyResearchCard({ companyId, enrichment = {}, status = 'not_researched' }: { companyId: string; enrichment?: Enrichment; status?: string }) {
  const [data, setData] = useState<Enrichment>(enrichment); const [state, setState] = useState(status); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const research = async () => { setBusy(true); setError(null); const response = await researchCompanyWebsite(companyId); setBusy(false); if (!response.success) { setError(response.error); return }; setData(response.data); setState('needs_review') }
  const verify = async () => { setBusy(true); const response = await saveCompanyEnrichment(companyId, { ceo: data.ceo || null, founders: data.founders || [], foundingYear: data.foundingYear || null, sources: data.sources || [], status: 'verified' }); setBusy(false); if (!response.success) setError(response.error); else { setState('verified'); window.location.reload() } }
  return <div className="rounded-card border border-border-hairline bg-shell p-5 shadow-sm"><div className="mb-3 flex items-start justify-between gap-3"><div><h3 className="text-[15px] font-semibold text-text-primary">Company research</h3><p className="mt-1 text-[11px] text-text-muted">Website-derived facts need officer verification before use.</p></div><span className={`rounded-pill px-2 py-1 text-[10px] font-medium ${state === 'verified' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{state.replace('_', ' ')}</span></div>{error && <p className="mb-2 text-xs text-red-600">{error}</p>}<dl className="space-y-2 text-[12px]"><div className="flex justify-between gap-3"><dt className="text-text-muted">CEO</dt><dd className="text-right text-text-primary">{data.ceo || '—'}</dd></div><div className="flex justify-between gap-3"><dt className="text-text-muted">Founders</dt><dd className="text-right text-text-primary">{data.founders?.join(', ') || '—'}</dd></div><div className="flex justify-between gap-3"><dt className="text-text-muted">Founded</dt><dd className="text-right text-text-primary">{data.foundingYear || '—'}</dd></div></dl>{data.sources?.length ? <div className="mt-3 space-y-1 border-t border-border-hairline pt-3">{data.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="flex items-center gap-1 truncate text-[11px] text-blue-600 hover:underline"><ExternalLink className="h-3 w-3" />{source.label}</a>)}</div> : null}<div className="mt-4 flex gap-2"><button disabled={busy} onClick={research} className="flex items-center gap-1 rounded-pill border border-border-hairline px-3 py-1.5 text-xs text-text-secondary">{busy ? <Loader2 className="h-3 w-3 animate-spin" /> : <Search className="h-3 w-3" />}Research website</button>{state === 'needs_review' && <button disabled={busy} onClick={verify} className="flex items-center gap-1 rounded-pill bg-emerald-600 px-3 py-1.5 text-xs text-white"><CheckCircle2 className="h-3 w-3" />Verify</button>}</div></div>
}
