'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { format } from 'date-fns'
import { updateOpportunityStage } from '@/app/actions/opportunities'

export interface PipelineOpportunity { id: string; title: string; type: string | null; stage: string; probability: number | null; expected_close: string | null; company_id: string; companyName: string | null; ownerName: string | null }

const STAGES = ['Prospect', 'Qualified', 'Meeting', 'Proposal Sent', 'Negotiation', 'Approved', 'Active', 'Completed', 'Lost']
const STAGE_COLORS: Record<string, { bg: string; text: string; border: string; header: string }> = {
  Prospect: { bg: 'bg-gray-50', text: 'text-gray-700', border: 'border-gray-200', header: 'bg-gray-100' }, Qualified: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200', header: 'bg-blue-100' }, Meeting: { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200', header: 'bg-indigo-100' }, 'Proposal Sent': { bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200', header: 'bg-purple-100' }, Negotiation: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200', header: 'bg-amber-100' }, Approved: { bg: 'bg-teal-50', text: 'text-teal-700', border: 'border-teal-200', header: 'bg-teal-100' }, Active: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', header: 'bg-emerald-100' }, Completed: { bg: 'bg-green-50', text: 'text-green-700', border: 'border-green-200', header: 'bg-green-100' }, Lost: { bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200', header: 'bg-red-100' },
}

export function OpportunityBoard({ opportunities }: { opportunities: PipelineOpportunity[] }) {
  const router = useRouter(); const [draggedId, setDraggedId] = useState<string | null>(null); const [savingId, setSavingId] = useState<string | null>(null)
  const byStage = Object.fromEntries(STAGES.map(stage => [stage, opportunities.filter(opportunity => opportunity.stage === stage)])) as Record<string, PipelineOpportunity[]>
  const move = async (stage: string) => { if (!draggedId) return; setSavingId(draggedId); const response = await updateOpportunityStage(draggedId, stage); if (!response.success) window.alert(response.error); setDraggedId(null); setSavingId(null); router.refresh() }
  return <div className="flex gap-4 h-full" style={{ minWidth: `${STAGES.length * 240}px` }}>{STAGES.map(stage => { const colors = STAGE_COLORS[stage]; const cards = byStage[stage] || []; return <div key={stage} className="flex flex-col w-56 flex-shrink-0" onDragOver={event => event.preventDefault()} onDrop={() => move(stage)}><div className={`px-3 py-2 rounded-t-[12px] ${colors.header} border ${colors.border} border-b-0 flex items-center justify-between`}><span className={`text-[12px] font-semibold ${colors.text}`}>{stage}</span><span className={`text-[11px] font-medium px-2 py-0.5 rounded-full bg-white/60 ${colors.text}`}>{cards.length}</span></div><div className={`flex-1 overflow-y-auto rounded-b-[12px] border ${colors.border} ${colors.bg} p-2 space-y-2 min-h-[200px]`}>{cards.map(opportunity => <div key={opportunity.id} draggable={savingId !== opportunity.id} onDragStart={() => setDraggedId(opportunity.id)} className={`cursor-grab active:cursor-grabbing ${savingId === opportunity.id ? 'opacity-50' : ''}`}><Link href={`/companies/${opportunity.company_id}`}><div className="bg-shell rounded-[10px] p-3 border border-border-hairline shadow-sm hover:shadow-md transition-shadow"><p className="font-semibold text-text-primary text-[13px] leading-tight mb-1">{opportunity.title}</p><p className="text-[11px] text-text-secondary mb-2">{opportunity.companyName || 'Company unavailable'}</p>{opportunity.type && <span className="inline-block px-2 py-0.5 bg-subtle border border-border-hairline rounded-pill text-[10px] text-text-muted font-medium mb-2">{opportunity.type}</span>}<div className="flex items-center justify-between mt-1">{opportunity.probability !== null && <div className="flex items-center gap-1"><div className="h-1 bg-border-hairline rounded-full w-16 overflow-hidden"><div className="h-1 bg-blue-400 rounded-full" style={{ width: `${opportunity.probability}%` }} /></div><span className="text-[10px] text-text-muted">{opportunity.probability}%</span></div>}{opportunity.ownerName && <div className="w-5 h-5 rounded-full bg-blue-500 text-white flex items-center justify-center text-[9px] font-bold" title={opportunity.ownerName}>{opportunity.ownerName.substring(0, 2).toUpperCase()}</div>}</div>{opportunity.expected_close && <p className="text-[10px] text-text-muted mt-1.5">Close: {format(new Date(opportunity.expected_close), 'MMM d, yyyy')}</p>}</div></Link></div>)}{cards.length === 0 && <div className="text-center py-6 text-[11px] text-text-muted">Drop opportunities here</div>}</div></div>})}</div>
}
