-- CORA Phase 1 production core. Additive migration; existing legacy alumni tables remain intact.
create extension if not exists pgcrypto;

alter table public.companies add column if not exists size text, add column if not exists headquarters text, add column if not exists description text, add column if not exists tags text[] not null default '{}';
alter table public.contacts add column if not exists title text, add column if not exists department text, add column if not exists preferred_communication text, add column if not exists is_primary boolean not null default false;
alter table public.interactions add column if not exists participants text[] not null default '{}', add column if not exists next_action text, add column if not exists follow_up_date timestamptz, add column if not exists opportunity_id uuid;
alter table public.opportunities add column if not exists initiative_id uuid, add column if not exists notes text;
alter table public.follow_ups add column if not exists description text, add column if not exists reminder_schedule text;

create table if not exists public.attachments (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations(id) on delete cascade, company_id uuid references public.companies(id) on delete cascade, interaction_id uuid references public.interactions(id) on delete cascade, opportunity_id uuid references public.opportunities(id) on delete cascade, follow_up_id uuid references public.follow_ups(id) on delete cascade, uploaded_by uuid not null references public.users(id), storage_path text not null, file_name text not null, content_type text, file_size bigint, created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations(id) on delete cascade, actor_id uuid references public.users(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create table if not exists public.reminder_preferences (user_id uuid primary key references public.users(id) on delete cascade, org_id uuid not null references public.organizations(id) on delete cascade, in_app_enabled boolean not null default true, default_schedule text not null default '1 day');
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, follow_up_id uuid references public.follow_ups(id) on delete cascade, title text not null, body text, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.import_jobs (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations(id) on delete cascade, created_by uuid not null references public.users(id), entity_type text not null, file_name text not null, status text not null default 'preview', total_rows integer not null default 0, imported_rows integer not null default 0, error_rows integer not null default 0, errors jsonb not null default '[]', created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.initiative_supporters (initiative_id uuid not null references public.initiatives(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, org_id uuid not null references public.organizations(id) on delete cascade, primary key (initiative_id, user_id));
create table if not exists public.opportunity_supporters (opportunity_id uuid not null references public.opportunities(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, org_id uuid not null references public.organizations(id) on delete cascade, primary key (opportunity_id, user_id));

alter table public.interactions drop constraint if exists interactions_opportunity_id_fkey;
alter table public.interactions add constraint interactions_opportunity_id_fkey foreign key (opportunity_id) references public.opportunities(id) on delete set null;
alter table public.opportunities drop constraint if exists opportunities_initiative_id_fkey;
alter table public.opportunities add constraint opportunities_initiative_id_fkey foreign key (initiative_id) references public.initiatives(id) on delete set null;

create unique index if not exists one_active_primary_owner_per_company on public.relationship_assignments(company_id) where assignment_type = 'PRIMARY' and is_active = true;
create unique index if not exists one_primary_contact_per_company on public.contacts(company_id) where is_primary = true;
create index if not exists companies_org_status_idx on public.companies(org_id, status);
create index if not exists interactions_org_date_idx on public.interactions(org_id, date desc);
create index if not exists follow_ups_org_due_idx on public.follow_ups(org_id, due_date);
create index if not exists opportunities_org_stage_idx on public.opportunities(org_id, stage);
create index if not exists audit_logs_org_created_idx on public.audit_logs(org_id, created_at desc);
do $$ declare t text; begin foreach t in array array['companies','relationship_assignments','interactions','follow_ups','opportunities'] loop if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t) then execute format('alter publication supabase_realtime add table public.%I', t); end if; end loop; end $$;

create or replace function public.current_user_role() returns text language sql stable security definer set search_path = public as $$ select role from public.users where id = auth.uid() $$;
create or replace function public.has_cora_role(allowed text[]) returns boolean language sql stable security definer set search_path = public as $$ select coalesce(public.current_user_role() = any(allowed), false) $$;
create or replace function public.audit_row_change() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.audit_logs(org_id, actor_id, action, entity_type, entity_id, before_data, after_data) values (coalesce(new.org_id, old.org_id), auth.uid(), tg_op, tg_table_name, coalesce(new.id, old.id), to_jsonb(old), to_jsonb(new)); return coalesce(new, old); end; $$;

do $$ declare t text; p record; begin foreach t in array array['companies','contacts','relationship_assignments','initiatives','interactions','follow_ups','opportunities','attachments','audit_logs','reminder_preferences','notifications','import_jobs','initiative_supporters','opportunity_supporters'] loop execute format('alter table public.%I enable row level security', t); for p in select policyname from pg_policies where schemaname='public' and tablename=t loop execute format('drop policy if exists %I on public.%I', p.policyname, t); end loop; execute format('create policy cora_select on public.%I for select using (org_id = public.get_current_org_id())', t); execute format('create policy cora_insert on public.%I for insert with check (org_id = public.get_current_org_id() and public.has_cora_role(array[''admin'',''manager'',''officer'',''student_assistant'']))', t); execute format('create policy cora_update on public.%I for update using (org_id = public.get_current_org_id() and public.has_cora_role(array[''admin'',''manager'',''officer'',''student_assistant''])) with check (org_id = public.get_current_org_id())', t); execute format('create policy cora_delete on public.%I for delete using (org_id = public.get_current_org_id() and public.has_cora_role(array[''admin'',''manager'']))', t); end loop; end $$;

drop trigger if exists audit_companies on public.companies; create trigger audit_companies after insert or update or delete on public.companies for each row execute function public.audit_row_change();
drop trigger if exists audit_assignments on public.relationship_assignments; create trigger audit_assignments after insert or update or delete on public.relationship_assignments for each row execute function public.audit_row_change();
drop trigger if exists audit_interactions on public.interactions; create trigger audit_interactions after insert or update or delete on public.interactions for each row execute function public.audit_row_change();
drop trigger if exists audit_follow_ups on public.follow_ups; create trigger audit_follow_ups after insert or update or delete on public.follow_ups for each row execute function public.audit_row_change();
drop trigger if exists audit_opportunities on public.opportunities; create trigger audit_opportunities after insert or update or delete on public.opportunities for each row execute function public.audit_row_change();

create or replace function public.refresh_overdue_follow_ups() returns void language sql security definer set search_path = public as $$ update public.follow_ups set status = 'Overdue', updated_at = now() where due_date < now() and status in ('Pending', 'In Progress'); $$;
create or replace function public.find_duplicate_outreach(p_company_id uuid, p_initiative_id uuid default null) returns table(interaction_id uuid, interaction_date timestamptz, follow_up_id uuid, owner_id uuid) language sql stable security invoker as $$ select i.id, i.date, f.id, ra.user_id from public.interactions i left join public.follow_ups f on f.interaction_id=i.id and f.status not in ('Completed','Cancelled') left join public.relationship_assignments ra on ra.company_id=i.company_id and ra.assignment_type='PRIMARY' and ra.is_active where i.company_id=p_company_id and (p_initiative_id is null or i.initiative_id=p_initiative_id) and i.date > now() - interval '30 days' order by i.date desc limit 20 $$;
