import { Search as SearchIcon, Building2, BriefcaseBusiness, ClipboardCheck, User } from 'lucide-react'
import { fullTextSearch, type SearchResult } from '@/app/actions/search'
import Link from 'next/link'

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = (await searchParams).q?.trim() ?? ''
  let results: SearchResult[] = []
  if (query) { const response = await fullTextSearch(query); if (response.success) results = response.data }
  const iconFor = (type: SearchResult['type']) => type === 'company' ? <Building2 className="w-5 h-5 text-blue-500" /> : type === 'opportunity' ? <BriefcaseBusiness className="w-5 h-5 text-purple-500" /> : type === 'follow_up' ? <ClipboardCheck className="w-5 h-5 text-amber-500" /> : <User className="w-5 h-5 text-green-500" />
  return <div className="w-full max-w-4xl mx-auto space-y-8 animate-in fade-in duration-500 pb-20"><div className="bg-white p-8 rounded-3xl border border-gray-100 text-center"><h1 className="text-3xl font-semibold text-gray-800 mb-2">Global Search</h1><p className="text-gray-500 mb-8">Search companies, contacts, officers, opportunities, interactions, and follow-ups.</p><form className="max-w-xl mx-auto relative"><SearchIcon className="absolute left-4 top-4 h-5 w-5 text-gray-400" /><input type="text" name="q" defaultValue={query} className="block w-full pl-12 pr-24 py-4 bg-gray-50 rounded-2xl outline-none focus:ring-2 focus:ring-blue-500/50 text-gray-800" placeholder="Search CORA..." /><button type="submit" className="absolute inset-y-2 right-2 px-6 bg-blue-500 hover:bg-blue-600 text-white rounded-xl font-medium">Search</button></form></div>{query && <div className="space-y-4"><p className="text-gray-600">Search results for: <span className="bg-gray-100 px-3 py-1 rounded-full text-sm">{query}</span></p>{results.length === 0 ? <div className="bg-white p-8 rounded-2xl text-center text-gray-500">No results found.</div> : results.map(result => <Link key={`${result.type}-${result.id}`} href={result.href} className="flex items-center gap-4 bg-white p-4 rounded-2xl border border-gray-100 hover:border-blue-300 hover:shadow-md"><div>{iconFor(result.type)}</div><div><h3 className="font-medium text-gray-800">{result.title}</h3><p className="text-sm text-gray-500">{result.subtitle ?? result.type}</p></div><span className="ml-auto text-xs capitalize text-gray-400">{result.type.replace('_', ' ')}</span></Link>)}</div>}</div>
}
