'use server'
import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { requirePermission } from '@/lib/authz'
import { withActionHandler } from '@/lib/actions-wrapper'
import { formString } from '@/lib/validation'

export const getInitiatives = async (companyId: string) => withActionHandler(async () => { const user = await requirePermission('read'); const { data, error } = await (await createClient()).from('initiatives').select('id, company_id, name, type, owner_id, status, priority, created_at, owner:owner_id(id, full_name)').eq('org_id', user.orgId).eq('company_id', companyId).order('created_at', { ascending: false }); if (error) throw new Error(`DATABASE: ${error.message}`); return data ?? [] })
export const createInitiative = async (formData: FormData) => withActionHandler(async () => { const user = await requirePermission('write'); const companyId = formString(formData, 'company_id'); const name = formString(formData, 'name'); if (!companyId || !name) throw new Error('VALIDATION: Company and initiative name are required'); const supabase = await createClient(); const { data, error } = await supabase.from('initiatives').insert({ org_id: user.orgId, company_id: companyId, name, type: formString(formData, 'type'), owner_id: formString(formData, 'owner_id'), status: formString(formData, 'status') ?? 'Active', priority: formString(formData, 'priority') }).select().single(); if (error) throw new Error(`DATABASE: ${error.message}`); revalidatePath(`/companies/${companyId}`); return data })
export const updateInitiative = async (id: string, formData: FormData) => withActionHandler(async () => { await requirePermission('write'); const supabase = await createClient(); const { data, error } = await supabase.from('initiatives').update({ name: formString(formData, 'name'), type: formString(formData, 'type'), owner_id: formString(formData, 'owner_id'), status: formString(formData, 'status'), priority: formString(formData, 'priority'), updated_at: new Date().toISOString() }).eq('id', id).select('id, company_id').single(); if (error) throw new Error(`DATABASE: ${error.message}`); revalidatePath(`/companies/${data.company_id}`); return data })
