'use server'

import { createClient } from '@/lib/supabase/server'
import { requirePermission } from '@/lib/authz'
import { withActionHandler } from '@/lib/actions-wrapper'
import { toCsv, parseCsv } from '@/lib/csv'
import { revalidatePath } from 'next/cache'

const TABLES = { companies: 'companies', contacts: 'contacts', interactions: 'interactions', follow_ups: 'follow_ups', opportunities: 'opportunities', ownership: 'relationship_assignments' } as const
export type ReportEntity = keyof typeof TABLES

export const getAnalytics = async (filters?: { from?: string; to?: string; industry?: string; status?: string; officerId?: string; opportunityType?: string }) => withActionHandler(async () => {
  const user = await requirePermission('view_analytics'); const supabase = await createClient(); const from = filters?.from ?? new Date(new Date().getFullYear(), 0, 1).toISOString(); const to = filters?.to ?? new Date().toISOString()
  let companiesQuery = supabase.from('companies').select('id, name, industry, status, created_at').eq('org_id', user.orgId); if (filters?.industry) companiesQuery = companiesQuery.eq('industry', filters.industry); if (filters?.status) companiesQuery = companiesQuery.eq('status', filters.status)
  const [companies, interactions, followUps, opportunities, assignments] = await Promise.all([companiesQuery, supabase.from('interactions').select('id, type, date, company_id').eq('org_id', user.orgId).gte('date', from).lte('date', to), supabase.from('follow_ups').select('id, status, due_date, officer_id').eq('org_id', user.orgId), supabase.from('opportunities').select('id, stage, type, initiative_owner_id, probability').eq('org_id', user.orgId), supabase.from('relationship_assignments').select('company_id, user_id, assignment_type').eq('org_id', user.orgId).eq('is_active', true)])
  for (const response of [companies, interactions, followUps, opportunities, assignments]) if (response.error) throw new Error(`DATABASE: ${response.error.message}`)
  const companyRows = companies.data ?? []; const followUpRows = followUps.data ?? []; const opportunityRows = opportunities.data ?? []; const now = Date.now()
  return { kpis: { totalCompanies: companyRows.length, activePartners: companyRows.filter(row => row.status === 'Active Partner').length, dormantCompanies: companyRows.filter(row => row.status === 'Dormant').length, newCompanies: companyRows.filter(row => new Date(row.created_at).getMonth() === new Date().getMonth()).length, meetings: (interactions.data ?? []).filter(row => row.type === 'Meeting').length, pendingFollowUps: followUpRows.filter(row => !['Completed', 'Cancelled'].includes(row.status)).length, overdueFollowUps: followUpRows.filter(row => !['Completed', 'Cancelled'].includes(row.status) && row.due_date && new Date(row.due_date).getTime() < now).length, totalOpportunities: opportunityRows.length, activeOpportunities: opportunityRows.filter(row => !['Completed', 'Lost'].includes(row.stage)).length }, companies: companyRows, interactions: interactions.data ?? [], followUps: followUpRows, opportunities: opportunityRows, assignments: assignments.data ?? [] }
})

export const exportReport = async (entity: ReportEntity) => withActionHandler(async () => { const user = await requirePermission('export'); const table = TABLES[entity]; const supabase = await createClient(); const { data, error } = await supabase.from(table).select('*').eq('org_id', user.orgId).limit(10000); if (error) throw new Error(`DATABASE: ${error.message}`); const rows = (data ?? []) as Record<string, unknown>[]; return { filename: `cora-${entity}-${new Date().toISOString().slice(0, 10)}.csv`, content: toCsv(rows), count: rows.length } })

export const importCompaniesCsv = async (csv: string) => withActionHandler(async () => { const user = await requirePermission('write'); const rows = parseCsv(csv); if (rows.length < 2) throw new Error('VALIDATION: CSV must include a header and at least one row'); const headers = rows[0].map(header => header.toLowerCase().replace(/\s+/g, '_')); const required = ['name']; if (!required.every(field => headers.includes(field))) throw new Error('VALIDATION: CSV must include a name column'); const supabase = await createClient(); const records = rows.slice(1).map(values => Object.fromEntries(headers.map((header, index) => [header, values[index] ?? '']))).filter(record => record.name).map(record => ({ org_id: user.orgId, name: record.name, industry: record.industry || null, status: record.status || 'Prospect', website: record.website || null, notes: record.notes || null })); const { data, error } = await supabase.from('companies').insert(records).select('id'); if (error) throw new Error(`DATABASE: ${error.message}`); revalidatePath('/companies'); revalidatePath('/'); return { imported: data?.length ?? 0, errors: [] as string[] } })
